def words_importation(dico):
    return dico

words_dico = {
    "facile" : [
        "abeille",
        "abri",
        "accord",
        "actif",
        "album",
        "aller",
        "amour",
        "arbre",
        "argent",
        "avion",
        "bébé",
        "bien",
        "bleu",
        "bois",
        "bon",
        "bouc",
        "bout",
        "bruit",
        "chat",
        "chien",
        "dire",
        "école",
        "faire",
        "haut",
        "jour",
        "livre",
        "main",
        "mal",
        "mer",
        "mètre",
        "mot",
        "noir",
        "nuit",
        "ombre",
        "oui",
        "pain",
        "père",
        "petit",
        "pluie",
        "rouge",
        "salle",
        "sang",
        "seul",
        "table",
        "temps",
        "tête",
        "tirer",
        "vert",
        "voir"
        ],

    "moyen" : [
        "Chocolat",
        "Lapinous",
        "Bonjourn",
        "Jardinier",
        "Montagne",
        "Aviation",
        "Bateaux",
        "Livretsin",
        "Caméras",
        "Tapisser",
        "Étoiles",
        "Pluviomètre",
        "Châteaux",
        "Violente",
        "Pianiste",
        "Alphabet",
        "Cascade",
        "Aventure",
        "Banquier",
        "Cuisiner",
        "Liberté",
        "Randonnée",
        "Trésorerie",
        "Anniversaire",
        "Caméléon",
        "Danseuse",
        "Explosion",
        "Eau-forte",
        "Horloge",
        "Jalouse",
        "Kangourou",
        "Mélodie",
        "Papillon",
        "Théière"
        ],

    "difficile" : [
        "Bibliothèque",
        "Chocolaterie",
        "Anticonstitutionnellement",
        "Incompréhensibilité",
        "Indivisibilité",
        "Phénoménologiquement",
        "Électroencéphalographie",
        "Parallélogramme",
        "Hypothalamique",
        "Supercalifragilisticexpialidocious",
        "Constitutionnalité",
        "Thermodynamiquement",
        "Démocratiquement",
        "Inintelligibilité",
        "Inconstitutionnalité",
        "Intercontinentalité",
        "Rhinocéros",
        "Philosophiquement",
        "Autoantonyme",
        "Hippopotame"
        ]
}

words_importation(dico = words_dico)